package A1;

import java.util.concurrent.CancellationException;
import kotlin.Metadata;

@Metadata(d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0003\n\u0002\b\u0003\bÀ\u0002\u0018\u00002\u00060\u0001j\u0002`\u0002B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u000f\u0010\u0006\u001a\u00020\u0005H\u0016¢\u0006\u0004\b\u0006\u0010\u0007¨\u0006\b"}, d2 = {"LA1/d;", "Ljava/util/concurrent/CancellationException;", "Lkotlinx/coroutines/CancellationException;", "<init>", "()V", "", "fillInStackTrace", "()Ljava/lang/Throwable;", "ui_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
/* renamed from: A1.d  reason: case insensitive filesystem */
public final class C4337d extends CancellationException {

    /* renamed from: a  reason: collision with root package name */
    public static final C4337d f4397a = new C4337d();

    private C4337d() {
    }

    public Throwable fillInStackTrace() {
        setStackTrace(V.f4364a);
        return this;
    }
}
